---
- name: Deploy namespace
  import_tasks: create_namespace.yml

- name: Deploy secret
  import_tasks: create_secret.yml

- name: Deploy deployment
  import_tasks: create_deployment.yml

- name: Deploy service
  import_tasks: create_service.yml
