apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: judilibre-admin-sops
spec:
    secretTemplates:
        - name: judilibre-admin-http-passwd
          labels:
            app: judilibre-admin
          data:
            http-passwd: ENC[AES256_GCM,data:vPqiIW2jOZU=,iv:s+BrQmSeEnvlNAi1wbhQA38k5lhzjqXksn3mDMQ2TTY=,tag:/trxCun32a03jjWNwhnwqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTHEzUGJVV2JvdjBBdXdj
            VThRbjNtOHpSRXIwNHlPOWFLUjBBVmdXczBnCnQ3a0pxUjhCS0tJcUNKaTF6OXpC
            b3l2a25VelNyUXlVWHB4SGNnMExkV00KLS0tIFkwdlBXUHYxRllGMW9Hd1ZhSU5R
            RnFwTVQ0a281N05hVkVHY041ZG1ZYU0Ksh76b2Sj1E/yKtAaEW7+roPVil4rji/m
            ZqmZi+aOK7ZssTecQjGEkPRXwOzUIiFM38Qf4pmcHYW/YUx4G2FwkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T09:49:18Z"
    mac: ENC[AES256_GCM,data:RA/2Z+j1MD4I0/zEPkQT1TWYu9UgOgWgSyaG6fEs9OK74T8TLS25hF3yNnIxWZlgq6rBzfiZ0Xp7CaMelGPxEoiK9YSXaGtpR0b69K7lUlJyk+hDAwtBlUC5rBRdssklPat3o97PSneIbq4yiQPZNqrdjiJ70jD+rE7KxKKCPbI=,iv:4UYYKMpwMxNmF2Cd+GVDKCVcoDfGOD5yIdhVLYDBrLs=,tag:EKP+5bOITkRj4/a8ORvkOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
