apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: judilibre-admin-sops
spec:
  secretTemplates:
  - name: judilibre-admin-http-passwd
    labels:
      app: judilibre-admin
    data:
      http-passwd: changeme
