apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${APP_ID}-cert-${ACME}
  namespace: ${KUBE_NAMESPACE}
spec:
  commonName: ${APP_HOST}
  secretName: ${APP_ID}-cert-${ACME}
  dnsNames:
    - ${APP_HOST}
  issuerRef:
    name: letsencrypt-${ACME}
    kind: Issuer
${CERT_ALTER_SPEC}