apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_ID}-deployment
  namespace: ${KUBE_NAMESPACE}
spec:
  replicas: ${APP_NODES}
  selector:
    matchLabels:
      app: ${APP_ID}
  template:
    metadata:
      labels:
        app: ${APP_ID}
    spec:
      containers:
      - name: ${APP_ID}
        image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
        ports:
        - containerPort: ${API_PORT}
        env:
          - name: ELASTIC_NODE
            value: "https://${ELASTIC_APP_USER}:${ELASTIC_APP_PASSWORD}@${APP_GROUP}-es-http:9200"
          - name: ELASTIC_INDEX
            value: ${ELASTIC_INDEX}

