apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ${APP_GROUP}
  namespace: ${KUBE_NAMESPACE}
spec:
  version: ${ELASTIC_VERSION}
  volumeClaimDeletePolicy: ${ELASTIC_STORAGE_POLICY}
  nodeSets:
  - name: default
    count: ${ELASTIC_NODES}
    config:
      xpack.security.enabled: false
    volumeClaimTemplates:
    - metadata:
        name: ${APP_GROUP}-es-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${ELASTIC_STORAGE_SIZE}
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms${ELASTIC_MEM_JVM} -Xmx${ELASTIC_MEM_JVM}
          resources:
            requests:
              memory: ${ELASTIC_MEM}
          readinessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: 9200
              scheme: HTTP
            periodSeconds: 3
            initialDelaySeconds: 3
          volumeMounts:
          - name: stopwords
            mountPath: /usr/share/elasticsearch/config/analysis/
        volumes:
        - name: stopwords
          configMap:
            name: ${APP_GROUP}-stopwords