apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ${APP_GROUP}
  namespace: ${KUBE_NAMESPACE}
spec:
  version: ${ELASTIC_VERSION}
  volumeClaimDeletePolicy: ${ELASTIC_STORAGE_POLICY}
  auth:
    fileRealm:
    - secretName: ${APP_GROUP}-es-users
    roles:
    - secretName: ${APP_GROUP}-es-roles
  nodeSets:
  - name: default
    count: ${ELASTIC_NODES}
    volumeClaimTemplates:
    - metadata:
        name: ${APP_GROUP}-es-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${ELASTIC_STORAGE_SIZE}
    podTemplate:
      metadata:
        labels:
          tuned.openshift.io/elasticsearch: ""
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms${ELASTIC_MEM_JVM} -Xmx${ELASTIC_MEM_JVM}
          resources:
            requests:
              memory: ${ELASTIC_MEM}
          volumeMounts:
          - name: stopwords
            mountPath: /usr/share/elasticsearch/config/analysis/
        volumes:
        - name: stopwords
          configMap:
            name: ${APP_GROUP}-stopwords
