apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APP_ID}-route
  namespace: ${KUBE_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
spec:
  tls:
  - hosts:
    - ${APP_HOST}
    secretName: ${APP_ID}-cert-${ACME}
  rules:
  - host: ${APP_HOST}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${APP_ID}-svc
            port:
              number: 80
