apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: ${KUBE_NAMESPACE}
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.10"
  # persistent: true
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: user
      db: admin
      passwordSecretRef:
        name: mongodb-user-password
      roles:
        - name: dbOwner
          db: admin
      scramCredentialsSecretName: user-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-user-password
  namespace: ${KUBE_NAMESPACE}
type: Opaque
stringData:
  password: ${MONGODB_PASSWORD}
