gitlab-ci-local --privileged --network gitlab-ci-local-network \
--volume /var/run/docker.sock:/var/run/docker.sock \
--volume $HOME/gitlab-ci-local/vault-password.secret:/secrets/vault-password.secret:ro \
--volume $HOME/gitlab-ci-local/k3d-kubeconfig.yaml:/root/.kube/config:ro \
--volume $HOME/gitlab-ci-local/local-python-packages:/usr/local/lib/python3.12/site-packages:ro \
--variable ANSIBLE_VAULT_PASS=/secrets/vault-password.secret \
--variable CI_REGISTRY=localhost:5000 \
--variable CI_REGISTRY_USER=test \
--variable CI_JOB_TOKEN=test \
--variable CI_COMMIT_BRANCH=local \
--variable CI_COMMIT_TAG=0.0.1 \
--variable HTTP_PROXY= \
--variable HTTPS_PROXY= 