- name: Deploy judilibre-admin on public platform
  hosts: localhost
  connection: local

  tasks:
    - name: Ensure kubernetes python library is installed
      ansible.builtin.pip:
        name: kubernetes
        state: present
      environment:
        http_proxy: "{{ http_proxy_dev }}"
        https_proxy: "{{ https_proxy_dev }}"
    - name: Mettre à jour l'image du deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: judilibre-admin
            namespace: judilibre
          spec:
            template:
              spec:
                containers:
                  - name: judilibre-admin
                    image: "{{ judilibre_admin_docker_image }}"
