name: Publish Docker image

on: [push]

jobs:
  build:
    name: 🐳 Build docker image
    runs-on: ubuntu-latest
    env:
      APP_GROUP: judilibre
      APP_HOST: admin.judilibre.local
      APP_ID: judilibre-admin
      APP_NODES: 1
      APP_PORT: 443
      API_PORT: 8080
      APP_SCHEME: https
      APP_SELF_SIGNED: true
      DOCKER_USERNAME: opendatajustice
      ELASTIC_INDEX: judilibre_0
      ELASTIC_NODES: 1
      ELASTIC_MEM: 1024Mi
      ELASTIC_MEM_JVM: 512m
      ELASTIC_STORAGE_POLICY: DeleteOnScaledownAndClusterDeletion
      ELASTIC_STORAGE_SIZE: 3Gi
      HTTP_PASSWD: ${{ secrets.HTTP_PASSWD }}
      KUBE_TYPE: k3s
      KUBE_ZONE: local
      START_TIMEOUT: 120
    steps:
      - uses: actions/checkout@v1
      - name: get version
        run: echo "##[set-output name=version;]$(cat package.json | jq -r '.version')-$(git rev-parse --short HEAD)"
        id: extract_version
      - name: extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | sed 's|^refs/heads/||;' | tr '/' '-')"
        id: extract_branch
      - name: 🐋 Build the master docker image
        run: ./scripts/docker-build.sh
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          VERSION: ${{ steps.extract_version.outputs.version }}
      - name: ☸️  Deploy local k8s services
        run: ./scripts/deploy_k8s_services.sh
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          VERSION: ${{ steps.extract_version.outputs.version }}
      - name: ✅ Execute minimal tests
        run: |
          export KUBE_NAMESPACE=${APP_GROUP}-${KUBE_ZONE}-${GIT_BRANCH}
          kubectl get pods --namespace=${KUBE_NAMESPACE}
          kubectl logs service/${APP_ID}-svc --namespace=${KUBE_NAMESPACE}
          ./scripts/test_minimal.sh
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          KUBECONFIG: /home/runner/.kube/config-local-k3s.yaml
      - name: 🚀 Push docker image
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        run: |
          echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push ${DOCKER_USERNAME}/${APP_ID}:${VERSION};
          docker tag ${DOCKER_USERNAME}/${APP_ID}:${VERSION} ${DOCKER_USERNAME}/${APP_ID}:${GIT_BRANCH}
          docker push ${DOCKER_USERNAME}/${APP_ID}:${GIT_BRANCH}
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          VERSION: ${{ steps.extract_version.outputs.version }}
  deploy-scw:
    name: 🚀 Deploy, update on Scaleway (dev) ☸️
    needs: build
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    env:
      ACME: acme
      APP_GROUP: judilibre
      APP_HOST: admin.dev-par1.judilibre.io
      APP_HOST_ALTER: admin.dev.judilibre.io
      APP_ID: judilibre-admin
      APP_NODES: 1
      APP_SCHEME: https
      APP_PORT: 443
      API_PORT: 8080
      DOCKER_USERNAME: opendatajustice
      ELASTIC_INDEX: judilibre_0
      ELASTIC_NODES: 3
      ELASTIC_MEM: 2048Mi
      ELASTIC_MEM_JVM: 1024m
      ELASTIC_SEARCH_PASSWORD: ${{ secrets.ELASTIC_SEARCH_PASSWORD }}
      ELASTIC_STORAGE_POLICY: DeleteOnScaledownOnly
      ELASTIC_STORAGE_SIZE: 20Gi
      HTTP_PASSWD: ${{ secrets.HTTP_PASSWD }}
      KUBE_INGRESS: nginx
      KUBE_NAMESPACE: judilibre-scw-dev-par1-dev
      KUBE_TYPE: k8s
      KUBE_ZONE: scw-dev-par1
      SCW_ZONE: fr-par-1
      SCW_KUBE_NODES: 1
      START_TIMEOUT: 240
    steps:
      - uses: actions/checkout@v1
      - name: get version
        run: echo "##[set-output name=version;]$(cat package.json | jq -r '.version')-$(git rev-parse --short HEAD)"
        id: extract_version
      - name: extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | sed 's|^refs/heads/||;' | tr '/' '-')"
        id: extract_branch
      - name: kube prerequisites
        run: |
          mkdir -p ${HOME}/.kube
          cat k8s/kubeconfig.yaml | envsubst > ~/.kube/config
        env:
          KUBE_CA: ${{ secrets.KUBE_SCW_CA }}
          KUBE_NAME: ${{ secrets.KUBE_SCW_NAME }}
          KUBE_TOKEN: ${{ secrets.KUBE_SCW_TOKEN }}
          KUBE_URL: ${{ secrets.KUBE_SCW_URL }}
          KUBE_USER: ${{ secrets.KUBE_SCW_USER }}
      - name: ☸️  Deploy remote k8s services
        run: ./scripts/deploy_k8s_services.sh
        env:
          VERSION: ${{ steps.extract_version.outputs.version }}
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          SCW_KUBE_PROJECT_NAME: judilibre-dev
          SCW_ZONE: fr-par-1
          SCW_LOG_BUCKET: ${{ secrets.SCW_LOG_BUCKET }}
          SCW_LOG_ACCESS_KEY: ${{ secrets.SCW_LOG_ACCESS_KEY }}
          SCW_LOG_SECRET_KEY: ${{ secrets.SCW_LOG_SECRET_KEY }}
      - name: 🚀 update ☸️
        run: |
          if [ "${GIT_BRANCH}" != "master" ];then
            export APP_HOST=admin.${GIT_BRANCH}.judilibre.io;
          fi;
          export KUBE_NAMESPACE=${APP_GROUP}-${KUBE_ZONE}-${GIT_BRANCH}
          ./scripts/update_app.sh
          kubectl get pods --namespace=${KUBE_NAMESPACE}
          kubectl logs service/${APP_ID}-svc --namespace=${KUBE_NAMESPACE}
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          START_TIMEOUT: 20
          VERSION: ${{ steps.extract_version.outputs.version }}
